# Generated by Django 3.0.6 on 2020-06-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_project_projecttag_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(null=True, to='crudApp.ProjectTag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_body',
            field=models.TextField(null=True),
        ),
    ]
