# Generated by Django 3.0.6 on 2020-06-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0004_auto_20200604_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='images/project_sample.jpg', upload_to='images/'),
        ),
    ]
