# Generated by Django 3.0.6 on 2020-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0005_auto_20200604_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(blank=True, to='crudApp.ProjectTag'),
        ),
    ]
