# Generated by Django 3.0.6 on 2020-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0006_auto_20200604_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_body',
            field=models.TextField(blank=True),
        ),
    ]
